import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

# Font Config:
[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular"}

[env]
  TERM = "xterm-256color"

[window]
opacity = 0.65

[shell]
program = "/bin/bash"
args = [ "--login",]

[window.padding]
x = 20
y = 20

[colors.primary]
background = "#1E1E2E"
foreground = "#CDD6F4"
